[[redirects]]
  from = "/x/*"
  to   = "/x/index.html"
  status = 200
  force = true

[[edge_functions]]
path = "/sites/*"
function = "link-map"

[[edge_functions]]
path = "/createsite/"
function = "create-site"

[[edge_functions]]
path = "/o/*"
function = "open-shortlink"

[[edge_functions]]
path = "/s/"
function = "create-shortlink"

[[edge_functions]]
path = "/ly/"
function = "shortlink"

[[edge_functions]]
path = "/se*"
function = "send"

[[edge_functions]]
path = "/hiya*"
function = "hello-world"

[build]
  functions = "marko-functions"      # <-- your functions folder

[dev]
  functions = "marko-functions"      # for `netlify dev`
