[[edge_functions]]
path = "/sites/*"
function = "link-map"

[[edge_functions]]
path = "/createsite/"
function = "create-site"

[[edge_functions]]
path = "/o/*"
function = "open-shortlink"

[[edge_functions]]
path = "/s/"
function = "create-shortlink"

[[edge_functions]]
path = "/se*"
function = "send"

[[edge_functions]]
path = "/get-data*"
function = "fetchSiteData"

[[edge_functions]]
path = "/hiya*"
function = "hello-world"


