# netlify.toml
[functions]
  directory = "netlify/marko-functions" # For regular Netlify functions

[edge_functions]
  directory = "netlify/edge-functions" # For Edge Functions
  path = "/hello"
  function = "hello"
