[[redirects]]
  from = "/x/*"
  to   = "/x/index.html"
  status = 200
  force = true
  
[[edge_functions]]
path = "/sites/*"
function = "link-map"

[[edge_functions]]
path = "/createsite/"
function = "create-site"

[[edge_functions]]
path = "/o/*"
function = "open-shortlink"

[[edge_functions]]
path = "/c/"
function = "create-shortlink"

[[edge_functions]]
path = "/ly/"
function = "shortlink"

[[edge_functions]]
path = "/se*"
function = "send"

[[edge_functions]]
path = "/hiya*"
function = "hello-world"

[build]
  functions = "marko-functions"      # <-- your functions folder
  command = ""      # no build step
  publish = "."         # or wherever your html lives

[dev]
  functions = "marko-functions"      # for `netlify dev`
    command = ""      # no build step
    publish = "."         # or wherever your html lives

[functions.generate-zk-proof]
  # Raise execution timeout to 26 seconds
  background = true
