# netlify.toml
[functions]
  directory = "netlify/marko-functions" # For regular Netlify functions

[edge_functions]
  directory = "netlify/edge-functions" # For Edge Functions
  [[edge_functions.onRequest]]
    path = "/hello"
    function = "hello-world"
